services:
  # Service Backend
  - type: web
    name: nexus-server
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.0.0

  # Service Frontend
  - type: static
    name: nexus-frontend
    runtime: static
    buildCommand: npm install && npm run build
    publishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html